version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: dev.dockerfile
    env_file: ./config/env/dev.env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
